### PR TITLE
Fix large file corruption

### LINKED ISSUE #243: File corruption on Windows
Any call to `Longtail_{Write,Read}` will break for files >4GB on Windows.

`(DWORD)length` is 32 bits so these calls do not handle large files correctly:

```c
int Longtail_Read(HLongtail_OpenFile handle, uint64_t offset, uint64_t length, void* output)
{
    ...
    if (FALSE == ReadFile(h, output, (DWORD)length, 0, &ReadOp))
    ...
}

int Longtail_Write(HLongtail_OpenFile handle, uint64_t offset, uint64_t length, const void* input)
{
    ...
    if (FALSE == WriteFile(h, input, (DWORD)length, 0, &WriteOp))
    ...
}
```

Minimal repro:

```c
struct Longtail_StorageAPI* storage_api = Longtail_CreateFSStorageAPI();

// works:
//const uint64_t size = 4ULL * 1024ULL * 1024ULL * 1024ULL - 1ULL;

// corrupts file:
const uint64_t size = 4ULL * 1024ULL * 1024ULL * 1024ULL;

{
      Longtail_StorageAPI_HOpenFile file = NULL;
      int err = storage_api->OpenWriteFile(storage_api, path, 0, &file);
      if (err) { ... }
      char *wbuf = malloc(size);
      err = storage_api->Write(storage_api, file, 0, size, wbuf);
      if (err) { ... }
      free(wbuf);
      storage_api->CloseFile(storage_api, file);
}

{
      Longtail_StorageAPI_HOpenFile file = NULL;
      int err = storage_api->OpenReadFile(storage_api, path, &file);
      if (err) { ... }
      char *rbuf = malloc(size);
      err = storage_api->Read(storage_api, file, 0, size, rbuf);
      if (err) { ... }
      free(rbuf);
      storage_api->CloseFile(storage_api, file);
}
```

Side note: learned this after a Store Index for a particularly large store got randomly corrupted without any logs. The design with separate version store indices allowed us to still access historical data, "only" breaking new uploads. Very nice all things considered!

### PR DESCRIPTION
**Pull request by timsjostrand**
Fixes #243.

As reported in the original issue, calling `Longtail_Write` with large file sizes will corrupt those files. For the same reason `Longtail_Read` does not work for large files.

Originally detected on Win32, but  adding a test case (https://github.com/timsjostrand/longtail/pull/2/checks) revealed this is also the case on MacOS and Linux:
* Windows will fail silently, wrapping the file size around `DWORD_MAX`.
* MacOS will fail with errno 22 for large `length` values (seems to be ~2GB).
* Linux will write a max of 2GB for large `length` values, expecting the user to loop to write the rest.

Some notes:
* I had to revert the GitHub workflows to use `macos-13` instead of `macos-latest` since the `main` branch will not build currently.
* Win32 uses `DWORD_MAX` for the buffer chunk size. There is probably some perf gains in choosing a more optimal value since `DWORD_MAX` is quite slow.
* Linux/MacOS uses 4 MB for the buffer chunk size. MacOS in particular will throw errno 22 if `length` is too large. I'm guessing "too large" has something to do with `SSIZE_MAX` but the documentation is lacking.

### CODE REVIEW

File: lib/longtail_platform.c [hunk 1]
```diff
@@ -1066,19 +1066,30 @@ int Longtail_GetFilePermissions(const char* path, uint16_t* out_permissions)
     return 0;
 }
 
+#define LONGTAIL_WIN32_PART_SIZE(cur, end) \
```
Comment (DanEngelbrecht) [inline lib/longtail_platform.c:1069]: I'm not to fond of this macro - I'd rather have a definition like MAX_CHUNK_SIZE - preferrably a constant rather than a macro and write the terniary expression inline. It is just in two places one for read and one for write.

File: lib/longtail_platform.c [hunk 2]
```diff
@@ -1066,19 +1066,30 @@ int Longtail_GetFilePermissions(const char* path, uint16_t* out_permissions)
...
+    char* cur = (char*)output;
+    const char* end = cur + length;
+    while (cur < end)
     {
-        return Win32ErrorToErrno(GetLastError());
+        ReadOp.Offset  = (DWORD)(offset & 0xffffffff);
+        ReadOp.OffsetHigh = (DWORD)(offset >> 32);
+
+        const DWORD part_size = LONGTAIL_WIN32_PART_SIZE(cur, end);
+        if (FALSE == ReadFile(h, cur, part_size, 0, &ReadOp))
```
Comment (DanEngelbrecht) [inline lib/longtail_platform.c:1087]: We should make use of the fourth parameter - `lpNumberOfBytesRead` to determine how many bytes we actually read.

File: lib/longtail_platform.c [hunk 3]
```diff
@@ -1091,13 +1102,22 @@ int Longtail_Write(HLongtail_OpenFile handle, uint64_t offset, uint64_t length,
...
+    const char* cur = (const char*)input;
+    const char* end = cur + length;
+    while (cur < end)
     {
-        return Win32ErrorToErrno(GetLastError());
+        WriteOp.Offset  = (DWORD)(offset & 0xffffffff);
+        WriteOp.OffsetHigh = (DWORD)(offset >> 32);
+
+        const DWORD part_size = LONGTAIL_WIN32_PART_SIZE(cur, end);
+        if (FALSE == WriteFile(h, cur, part_size, 0, &WriteOp))
```
Comment (DanEngelbrecht) [inline lib/longtail_platform.c:1113]: We should make use of the fourth parameter - `lpNumberOfBytesWritten` to determine how many bytes we actually read.

File: test/test.cpp [hunk 4]
```diff
@@ -37,6 +37,13 @@
 #define TEST_LOG(fmt, ...) \
     fprintf(stderr, "--- ");fprintf(stderr, fmt, __VA_ARGS__);
 
+
+template<>
```
Comment (DanEngelbrecht) [inline test/test.cpp:41]: Is the template jc_test_print_value still in use or was it some temp code?

File: test/test.cpp [hunk 5]
```diff
@@ -8194,4 +8201,60 @@ TEST(Longtail, Longtail_CaseSensitivePaths)
     SAFE_DISPOSE_API(compression_registry);
     SAFE_DISPOSE_API(target_storage);
     SAFE_DISPOSE_API(source_storage);
+}
+
+TEST(Longtail, PlatformWriteLargeFile)
+{
+    static const uint64_t expected_size = 4ULL * 1024ULL * 1024ULL * 1024ULL;
```
Comment (DanEngelbrecht) [inline test/test.cpp:8208]: I don't think we should run these tests as default - creating a 4Gb file on each test run seems excessive.
Also, we could combine PlatformWriteLargeFile and PlatformReadLargeFile into one test so we don't have to generate the large file twice.

**Review by DanEngelbrecht — CHANGES_REQUESTED** [review]
Very nice - some minor things I'd like to see addressed.
I think we should separate out the workflow macos changes to a separate PR though.

File: lib/longtail_platform.c [hunk 6]
```diff
@@ -2215,10 +2246,17 @@ int Longtail_Write(HLongtail_OpenFile handle, uint64_t offset, uint64_t length,
...
 
     int fd = fileno(f);
-    ssize_t length_written = pwrite(fd, input, length, offset);
-    if (length_written == -1)
+    const char* cur = (const char*)input;
+    const char* end = cur + length;
+    while (cur < end)
     {
-        return errno;
+        ssize_t length_written = pwrite(fd, cur, LONGTAIL_PART_SIZE(cur, end), offset);
```
Comment (DanEngelbrecht) [inline lib/longtail_platform.c:2253]: Move calculation of size to read outside of call to pwrite please.

File: lib/longtail_platform.c [hunk 7]
```diff
@@ -2198,14 +2218,25 @@ int Longtail_GetFilePermissions(const char* path, uint16_t* out_permissions)
...
     FILE* f = (FILE*)handle;
     int fd = fileno(f);
-    ssize_t length_read = pread(fd, output, (off_t)length, (off_t)offset);
-    if (length_read == -1)
+    char* cur = (char*)output;
+    const char* end = cur + length;
+    while (cur < end)
     {
-        return errno;
+        ssize_t length_read = pread(fd, cur, LONGTAIL_PART_SIZE(cur, end), (off_t)offset);
```
Comment (DanEngelbrecht) [inline lib/longtail_platform.c:2233]: Move calculation of size to read outside of call to pwrite please.

File: lib/longtail_platform.c [hunk 8]
```diff
@@ -2198,14 +2218,25 @@ int Longtail_GetFilePermissions(const char* path, uint16_t* out_permissions)
     return res;
 }
 
+// Write/read in 4 MB chunks (__APPLE__ in particular will throw errno 22 if part_size is too large).
+#define LONGTAIL_PART_SIZE(cur, end) \
```
Comment (DanEngelbrecht) [inline lib/longtail_platform.c:2222]: Wondering if 4MB is good guess? Seems far from the problematic 2Gb limit.
Might want to go to 1GB or 512MB at least?
Or have you detected performance improvements with smaller write chunks?

File: lib/longtail_platform.c (hunk 2 above)
Comment (timsjostrand) [reply lib/longtail_platform.c:1087]: Agreed that using the actual bytes read/written is better.

There is some caveat to `lpNumberOfBytesRead` when using the optional `OVERLAPPED` parameter, but I don't remember the details. Will look into that.

File: test/test.cpp (hunk 4 above)
Comment (timsjostrand) [reply test/test.cpp:41]: This overload is still needed to make `ASSERT_EQ` (and friends) user friendly when asserting on uint64_t values.

Without overload:
`Expected: (actual_size) == (expected_size), actual: ? vs ?`

With overload:
`Expected: (actual_size) == (expected_size), actual: 2147479552 vs 4294967296`

File: lib/longtail_platform.c (hunk 1 above)
Comment (timsjostrand) [reply lib/longtail_platform.c:1069]: I tried to avoid "chunk" in the name because of the overloaded meaning in the code base, but agreed MAX_CHUNK_SIZE is a more common term for this.

File: lib/longtail_platform.c (hunk 8 above)
Comment (timsjostrand) [reply lib/longtail_platform.c:2222]: Definitely a guess!

Some quick non-scientific (!) tests on my Windows machine (64 GB RAM, 16 cores, current gen NVMe SSD):

| CHUNK_SIZE_MAX | PlatformWriteLargeFile | PlatformReadLargeFile |
|----------------|-----------|-----------|
| 1 MB           | 2.84916 s | 1.65695 s |
| 4 MB           | 1.98485 s | 1.70406 s |
| 16 MB          | 2.42341 s | 1.68393 s |
| 32 MB          | 3.01173 s | 1.68185 s |
| 64 MB          | 3.73048 s | 1.68759 s |
| 128 MB         | 3.73547 s | 1.68537 s |
| 512 MB         | 4.31509 s | 1.64977 s |
| DWORD_MAX      | 4.01439 s | 1.62759 s |

I don't have the facilities to do perf tests for MacOS or Linux in a real capacity (outside GitHub runners).

I think the real answer is likely "It Depends" -- operating system, disk type, driver, cache sizes etc. Finding the optimal max chunk size is probably a PR in its own right.

Are you comfortable using 4 MB as a starting point based on the above?

File: lib/longtail_platform.c (hunk 2 above)
Comment (timsjostrand) [reply lib/longtail_platform.c]: Updated in latest. The detail is that if the file was opened with `FILE_FLAG_OVERLAPPED` then `lpNumberOfBytesRead` must be NULL.

File: test/test.cpp (hunk 5 above)
Comment (timsjostrand) [reply test/test.cpp:8208]: Is there a way to express default/non-default in the testing framework or should I wrap them in `#if 0`?

Comment (DanEngelbrecht) [reply test/test.cpp:8208]: I don't think there is a non-default option. But just encapulate it inside a if (false) { } and it is easy to just change the flag.

File: lib/longtail_platform.c (hunk 8 above)
Comment (DanEngelbrecht) [reply lib/longtail_platform.c]: Feels off to use up to 4Gb on windows but 4Mb on other platforms?
Limit to 512Mb on all platforms?

Comment (DanEngelbrecht) [reply lib/longtail_platform.c]: Looking over the numbers, 4Mb on write seems faster in your test, but 512 Mb in read is faster...
Not sure what to do here...
Need a bigger set of sample data to do a proper guess.
We can have different limits for read and write for sure.

Comment (DanEngelbrecht) [reply lib/longtail_platform.c]: So quick test on my machine:
```
4Mb
Longtail_Write: 4.76223 s
Longtail_Read: 2.25163 s

8Mb
Longtail_Write: 4.22588 s
Longtail_Read: 2.32714 s

16Mb
Longtail_Write: 4.00197 s
Longtail_Read: 2.3902 s

32Mb
Longtail_Write: 4.32685 s
Longtail_Read: 2.87161 s

64Mb
Longtail_Write: 4.6808 s
Longtail_Read: 3.074 s

128Mb
Longtail_Write: 4.26141 s
Longtail_Read: 3.31375 s

256Mb
Longtail_Write: 4.3902 s
Longtail_Read: 3.56751 s

512Mb
Longtail_Write: 4.6452 s
Longtail_Read: 3.78527 s

```
So 4Mb if quickest for reads, 16Mb for writes.

The penalty for going to 16Mb for reads is smaller than the penalty for going with 4Mb for writes.

So I'm going to make a very grounded descision (lol) and say: 16Mb is a good chunk size :)

Comment (timsjostrand) [reply lib/longtail_platform.c]: 16 MB it is!

I guess a typical longtail-chunk will also fit inside a single read or write call then? (I'm not too familiar with how that chunk size is selected)

File: lib/longtail_platform.c [hunk 9]
```diff
@@ -5,6 +5,7 @@
 
 static const uint32_t HostnamePrime = 0x01000193;
 static const uint32_t HostnameSeed  = 0x811C9DC5;
+static const uint32_t MaxChunkSize  = 16777216;
```
Comment (DanEngelbrecht) [inline lib/longtail_platform.c:8]: Easier to read if `= 0x16 * 1024u * 1024u`

Comment (timsjostrand) [reply lib/longtail_platform.c]: You meant `16u * 1024u * 1024u`?

de5ac8e3d5ef7b157d6e97f6518ae1eb12599f46

**Review by DanEngelbrecht — APPROVED** [review]
Very nice.
Just make sure to fix the missing EOL at the end of test.cpp and we are good.

**Comment by timsjostrand** [comment]
EOL fixed in d62351c013a26b3677c4a92f77cf0c13c8140c51
